---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/work
    machine:
      image: circleci/classic:latest
    #docker:
    #- image: circleci/mariadb:10.2-bionic

    steps:
      - run: pwd; ls -al; id -a
      #- run: apt update &&
      #    apt install -y
      #    zip grep file ca-certificates autotools-dev autoconf automake
      #    git bc wget rsync make gzip tar

      - checkout
      - run: ls -al; pwd

      # compile
      - run: bash -x ./compile.sh
      - run: ldd ./scan_bar_codes
      - run: mkdir -p ~/work/deploy
      - run: cp -av ./scan_bar_codes ~/work/deploy/

      - store_artifacts:
          path: ~/work/deploy
          destination: deploy


